language: ruby

before_script:
  - psql -c 'create database timetracker_test;' -U postgres
  - bundle exec rake db:migrate

env:
  - DATABASE_URL=postgres://postgres@localhost/timetracker_test

rvm:
  - 2.2.3
  - jruby
  - rbx-2
addons:
  postgresql: "9.3"
