db:
  image: postgres
redis:
  image: redis
web:
  build: .
  environment:
    - RAILS_ENV=development
    - DATABASE_URL=postgres://postgres@db/postgres
  command: bundle exec rails s -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
    - redis
